[2025-04-16T13:39:17.571+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Stock_info_Proj.final_notification manual__2025-04-16T13:39:14.058702+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
